name: Java CI with JUnit

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '11'

    - name: Compile Java code
      run: javac -d target src/*.java

    - name: Run JUnit Tests
      run: java -cp target org.junit.runner.JUnitCore src.MainTest
