name: RunApp

on:
  push:
    branches:
      - master

jobs:
  run:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: 21  # Hier können Sie die gewünschte JDK-Version angeben
